# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Radix Sort Algorithm (C++)
NULL

tri_base_Rcpp <- function(v) {
    .Call(`_M2algorithmique_tri_base_Rcpp`, v)
}

quick_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_quick_sort_Rcpp`, v)
}

#' Merge Sort Algorithm (C++)
NULL

build_heap_Rcpp <- function(heap, i, n) {
    .Call(`_M2algorithmique_build_heap_Rcpp`, heap, i, n)
}

heap_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_heap_sort_Rcpp`, v)
}

tri_fusion_Rcpp <- function(v) {
    .Call(`_M2algorithmique_tri_fusion_Rcpp`, v)
}

